const spellingBeeData = [
  { word: "tag", level: "One Bee", origin: "Germanic", definition: "A label used for identification.", sentence: "Please write your name on the luggage tag." },
  { word: "send", level: "One Bee", origin: "English", definition: "To cause to go or be taken to a destination.", sentence: "I need to send this letter today." },
  { word: "deck", level: "One Bee", origin: "English", definition: "A flat surface capable of supporting weight, like a floor.", sentence: "We sat on the deck to watch the sunset." },
  { word: "stuck", level: "One Bee", definition: "Unable to move from a particular position.", sentence: "The zipper on my jacket is stuck." },
  { word: "snug", level: "One Bee", definition: "Comfortable, warm, and cozy.", sentence: "My new boots feel very snug and warm." },
  { word: "fish", level: "One Bee", definition: "A cold-blooded animal that lives in water and has gills.", sentence: "We saw a colorful fish swimming in the pond." },
  { word: "hold", level: "One Bee", definition: "To grasp or support with one's hands.", sentence: "Please hold the door open for me." },
  { word: "mind", level: "One Bee", definition: "The part of a person that thinks and feels.", sentence: "A positive mind helps you solve problems." },
  { word: "stay", level: "One Bee", definition: "To remain in a certain place.", sentence: "You should stay inside when it is raining." },
  { word: "scrub", level: "One Bee", definition: "To rub something hard to clean it.", sentence: "Use this brush to scrub the mud off your shoes." },
  { word: "draw", level: "One Bee", definition: "To produce a picture using lines.", sentence: "I like to draw pictures of animals." },
  { word: "brown", level: "One Bee", definition: "A dark color like soil or wood.", sentence: "The leaves turned brown as autumn arrived." },
  { word: "cozy", level: "One Bee", origin: "Scottish/Gaelic", definition: "Giving a feeling of comfort and warmth.", sentence: "It feels cozy to sit by the fireplace." },
  { word: "cosy", level: "One Bee", origin: "Scottish/Gaelic", definition: "Giving a feeling of comfort and warmth.", sentence: "The cat found a cosy spot for a nap." },
  { word: "tint", level: "One Bee", definition: "A slight or pale coloration.", sentence: "There was a pink tint in the sky at dawn." },
  { word: "milk", level: "One Bee", definition: "An opaque white liquid used for food.", sentence: "I poured a cold glass of milk." },
  { word: "yawn", level: "One Bee", definition: "To open the mouth wide and inhale due to tiredness.", sentence: "I couldn't help but yawn during the movie." },
  { word: "tank", level: "One Bee", definition: "A large container for liquid or gas.", sentence: "We filled the fish tank with fresh water." },
  { word: "want", level: "One Bee", definition: "To have a desire for something.", sentence: "Do you want to play soccer?" },
  { word: "crowd", level: "One Bee", definition: "A large number of people gathered together.", sentence: "A large crowd gathered to hear the band." },
  { word: "pond", level: "One Bee", definition: "A small body of still water.", sentence: "The ducks are swimming in the pond." },
  { word: "skirt", level: "One Bee", definition: "A garment hanging from the waist.", sentence: "She wore a floral skirt to the party." },
  { word: "sharks", level: "One Bee", definition: "Large predatory fish with cartilage skeletons.", sentence: "Some sharks live in the deep parts of the ocean." },
  { word: "quilt", level: "One Bee", definition: "A warm bedcover made of padded layers.", sentence: "My grandmother made a beautiful quilt." },
  { word: "twigs", level: "One Bee", definition: "Small, thin branches of a tree.", sentence: "The bird gathered small twigs for its nest." },
  { word: "taffy", level: "One Bee", definition: "A chewy candy made of boiled sugar.", sentence: "The salt-water taffy was sweet and chewy." },
  { word: "comfy", level: "One Bee", definition: "Informal for comfortable.", sentence: "This old armchair is very comfy." },
  { word: "stretch", level: "One Bee", definition: "To make something longer or wider by pulling.", sentence: "It is important to stretch before a run." },
  { word: "tight", level: "One Bee", definition: "Fixed or fastened firmly.", sentence: "The lid on the jar was closed too tight." },
  { word: "candy", level: "One Bee", definition: "A sweet food made with sugar.", sentence: "Don't eat too much candy before dinner." },
  { word: "scrunch", level: "One Bee", definition: "To squeeze something into a compact shape.", sentence: "I had to scrunch the paper to fit it in the bin." },
  { word: "ruby", level: "One Bee", definition: "A precious stone of a deep red color.", sentence: "The necklace featured a bright red ruby." },
  { word: "close", level: "One Bee", definition: "To move so as to cover an opening.", sentence: "Please close the window if you feel cold." },
  { word: "tackle", level: "One Bee", definition: "Equipment for a task; to deal with a problem.", sentence: "The football player made a great tackle." },
  { word: "wire", level: "One Bee", definition: "A thin, flexible thread of metal.", sentence: "The fence was made of strong metal wire." },
  { word: "skater", level: "One Bee", definition: "A person who glides on ice or wheels.", sentence: "The figure skater performed a perfect jump." },
  { word: "giant", level: "One Bee", definition: "An imaginary being of superhuman size.", sentence: "We saw a giant statue at the museum." },
  { word: "bucket", level: "One Bee", definition: "An open container with a handle for liquids.", sentence: "He carried a bucket of water to the garden." },
  { word: "chance", level: "One Bee", definition: "A possibility of something happening.", sentence: "There is a small chance of snow tonight." },
  { word: "baskets", level: "One Bee", definition: "Containers woven from canes or wire.", sentence: "The apples were collected in large baskets." },
  { word: "tender", level: "One Bee", definition: "Showing gentleness and concern.", sentence: "The meat was very tender and easy to eat." },
  { word: "paste", level: "One Bee", definition: "A thick, soft, moist substance.", sentence: "Use a little paste to stick the photos." },
  { word: "melon", level: "One Bee", definition: "A large, sweet fruit of the gourd family.", sentence: "We ate a slice of juicy melon at the picnic." },
  { word: "farmer", level: "One Bee", definition: "A person who manages a farm.", sentence: "The farmer planted rows of corn." },
  { word: "parent", level: "One Bee", definition: "A father or mother.", sentence: "Every parent wants their child to succeed." },
  { word: "tail", level: "One Bee", definition: "The hindmost part of an animal's body.", sentence: "The dog wagged its tail happily." },
  { word: "hockey", level: "One Bee", definition: "A team sport played with sticks and a puck or ball.", sentence: "Our school team won the hockey tournament." },
  { word: "slime", level: "One Bee", definition: "A moist, slippery, or sticky substance.", sentence: "Snails leave a trail of slime behind them." },
  { word: "insects", level: "One Bee", definition: "Small animals with six legs and three body parts.", sentence: "We studied various insects in science class." },
  { word: "teeth", level: "One Bee", definition: "Hard structures in the mouth used for chewing.", sentence: "You should brush your teeth every day." },
  { word: "shortcut", level: "One Bee", definition: "A shorter route than the usual one.", sentence: "We took a shortcut through the park." },
  { word: "bait", level: "One Bee", definition: "Food used to entice fish or animals.", sentence: "He put a worm on the hook as bait." },
  { word: "lure", level: "One Bee", definition: "To tempt a person or animal to go somewhere.", sentence: "The scent of flowers will lure bees." },
  { word: "cluster", level: "One Bee", definition: "A group of similar things positioned closely.", sentence: "A cluster of stars was visible in the sky." },
  { word: "forest", level: "One Bee", definition: "A large area covered chiefly with trees.", sentence: "It is easy to get lost in a thick forest." },
  { word: "hollow", level: "One Bee", definition: "Having an empty space inside.", sentence: "The squirrel hid nuts inside a hollow log." },
  { word: "spinning", level: "One Bee", definition: "Rotating rapidly around an axis.", sentence: "The dancer kept spinning across the stage." },
  { word: "baffling", level: "One Bee", definition: "Impossible to understand; confusing.", sentence: "The complex puzzle was completely baffling." },
  { word: "sizzling", level: "One Bee", definition: "Making a hissing sound from great heat.", sentence: "We could hear the bacon sizzling in the pan." },
  { word: "hoist", level: "One Bee", definition: "To raise or lift something.", sentence: "They used a crane to hoist the heavy engine." },
  { word: "search", level: "One Bee", definition: "To look carefully to find something.", sentence: "I had to search everywhere for my lost keys." },
  { word: "remind", level: "One Bee", definition: "To cause someone to remember something.", sentence: "Please remind me to call my sister." },
  { word: "mango", level: "One Bee", definition: "A fleshy yellowish-red tropical fruit.", sentence: "A ripe mango is sweet and delicious." },
  { word: "coral", level: "One Bee", definition: "A hard substance formed by skeletons of sea animals.", sentence: "We snorkeled to see the beautiful coral reef." },
  { word: "jangle", level: "One Bee", definition: "To make a harsh, ringing metallic sound.", sentence: "The keys in his pocket began to jangle." },
  { word: "shimmer", level: "One Bee", definition: "To shine with a soft, flickering light.", sentence: "We watched the sunlight shimmer on the lake." },
  { word: "blossoms", level: "One Bee", definition: "Flowers on a tree or plant.", sentence: "The cherry blossoms look beautiful in spring." },
  { word: "swampy", level: "One Bee", definition: "Soft, waterlogged ground.", sentence: "The ground near the river was very swampy." },
  { word: "studded", level: "One Bee", definition: "Decorated with small studs or spots.", sentence: "The night sky was studded with bright stars." },
  { word: "focus", level: "One Bee", definition: "The center of interest or activity.", sentence: "You must focus on your work to finish." },
  { word: "distress", level: "One Bee", definition: "Extreme anxiety, sorrow, or pain.", sentence: "The hiker sent a signal to show distress." },
  { word: "lessons", level: "One Bee", definition: "Periods of learning or teaching.", sentence: "I am taking piano lessons on Saturdays." },
  { word: "moment", level: "One Bee", definition: "A very brief period of time.", sentence: "Please wait for one moment while I find it." },
  { word: "ajar", level: "One Bee", definition: "Slightly open, as a door.", sentence: "He left the door ajar so the cat could get in." },
  { word: "basil", level: "One Bee", definition: "An aromatic herb used in cooking.", sentence: "Fresh basil adds flavor to pasta sauce." },
  { word: "triple", level: "One Bee", definition: "Consisting of three parts.", sentence: "I would like a triple scoop of ice cream." },
  { word: "satin", level: "One Bee", definition: "A smooth, glossy fabric.", sentence: "The bride wore a dress made of smooth satin." },
  { word: "ahoy", level: "One Bee", definition: "A shout used to hail a ship or person.", sentence: "'Ahoy there!' shouted the sailor." },
  { word: "signal", level: "One Bee", definition: "A gesture used to convey information.", sentence: "The green light is a signal to go." },
  { word: "answer", level: "One Bee", definition: "A spoken or written reply.", sentence: "I knew the correct answer to the question." },
  { word: "shuffle", level: "One Bee", definition: "To walk without lifting the feet fully.", sentence: "Please shuffle the deck of cards." },
  { word: "dollop", level: "One Bee", definition: "A shapeless mass of soft food.", sentence: "Add a dollop of whipped cream to the pie." },
  { word: "minnows", level: "One Bee", definition: "Very small freshwater fish.", sentence: "We caught some small minnows in our net." },
  { word: "silver", level: "One Bee", definition: "A shiny, grayish-white precious metal.", sentence: "My grandmother polished her silver spoons." },
  { word: "before", level: "One Bee", definition: "At an earlier time than.", sentence: "Wash your hands before you eat dinner." },
  { word: "circus", level: "One Bee", definition: "A traveling show of performers and animals.", sentence: "The circus performers did amazing tricks." },
  { word: "writing", level: "One Bee", definition: "The activity of marking coherent words.", sentence: "Clear writing helps people understand." },
  { word: "kitchen", level: "One Bee", definition: "A room where food is prepared.", sentence: "The smell of baking filled the kitchen." },
  { word: "sugar", level: "One Bee", definition: "A sweet substance from plants.", sentence: "I like to put a little sugar in my tea." },
  { word: "awkward", level: "One Bee", definition: "Causing or feeling embarrassment.", sentence: "There was an awkward silence in the room." },
  { word: "seep", level: "One Bee", definition: "To leak slowly through small holes.", sentence: "Water began to seep through the crack." },
  { word: "sweet", level: "One Bee", definition: "Having a taste like sugar.", sentence: "These strawberries are very sweet." },
  { word: "wheels", level: "One Bee", definition: "Circular frames that revolve on an axle.", sentence: "The car wheels spun on the wet road." },
  { word: "faint", level: "One Bee", definition: "Feeling weak and dizzy.", sentence: "I can hear a faint sound of music." },
  { word: "fruit", level: "One Bee", definition: "The edible part of a plant containing seeds.", sentence: "An apple is a healthy fruit to eat." },
  { word: "roam", level: "One Bee", definition: "To travel aimlessly.", sentence: "Cattle like to roam freely across fields." },
  { word: "goats", level: "One Bee", definition: "Hardy mammals with horns and beards.", sentence: "The goats climbed onto the rocky ledge." },
  { word: "woozy", level: "One Bee", definition: "Unsteady and dizzy.", sentence: "I felt a little woozy after spinning." },
  { word: "limbs", level: "One Bee", definition: "Arms or legs.", sentence: "The tree's limbs stretched over the roof." },
  { word: "ahead", level: "One Bee", definition: "Further forward in space or time.", sentence: "Look ahead to see what is coming." },
  { word: "señor", level: "One Bee", origin: "Spanish", definition: "A Spanish title of respect for a man.", sentence: "'Good morning, señor,' said the waiter." },
  { word: "unicorn", level: "One Bee", definition: "A mythical horse with a single horn.", sentence: "The child drew a magical unicorn." },
  { word: "faraway", level: "One Bee", definition: "Distant in space or time.", sentence: "She dreamed of traveling to faraway lands." },
  { word: "heater", level: "One Bee", definition: "A device used for warming something.", sentence: "We turned on the heater because it was cold." },
  { word: "pirates", level: "One Bee", definition: "People who attack ships at sea to steal.", sentence: "The story was about pirates and gold." },
  { word: "understand", level: "One Bee", definition: "To perceive the intended meaning.", sentence: "Do you understand this math problem?" },
  { word: "wooden", level: "One Bee", definition: "Made of wood.", sentence: "The old house had beautiful wooden floors." },
  { word: "leaning", level: "One Bee", definition: "Being in a sloping position.", sentence: "The old tower is leaning to one side." },
  { word: "breakfast", level: "One Bee", definition: "The first meal of the day.", sentence: "I usually have eggs for breakfast." },
  { word: "window", level: "One Bee", definition: "An opening in a wall fitted with glass.", sentence: "I looked out the window at the birds." },
  { word: "acrobat", level: "One Bee", definition: "A person who performs gymnastic feats.", sentence: "The acrobat performed a daring flip." },
  { word: "message", level: "One Bee", definition: "A communication sent from one to another.", sentence: "I left a message on your phone." },
  { word: "chocolate", level: "One Bee", definition: "A food made from roasted cacao seeds.", sentence: "Dark chocolate is my favorite candy." },
  { word: "forepaw", level: "One Bee", definition: "A front paw of an animal.", sentence: "The cat licked its forepaw after eating." },
  { word: "elephant", level: "One Bee", definition: "A very large mammal with a trunk and tusks.", sentence: "An elephant uses its trunk to eat." },
  { word: "hedgehog", level: "One Bee", definition: "A small mammal with a spiny coat.", sentence: "The hedgehog curled into a protective ball." },
  { word: "recipe", level: "One Bee", definition: "Instructions for preparing a dish.", sentence: "I followed a new recipe to bake a cake." },
  { word: "garbage", level: "One Bee", definition: "Wasted or spoiled food; refuse.", sentence: "Please take the garbage out to the bin." },
  { word: "surprise", level: "One Bee", definition: "An unexpected event.", sentence: "We planned a surprise party for him." },
  { word: "mermaid", level: "One Bee", definition: "A mythical sea creature, half woman, half fish.", sentence: "Legend says the mermaid sang to sailors." },
  { word: "bombarded", level: "One Bee", definition: "Attacked continuously.", sentence: "The teacher was bombarded with questions." },
  { word: "disability", level: "One Bee", definition: "A physical or mental condition that limits a person.", sentence: "The building has ramps for disability access." },
  { word: "incredible", level: "One Bee", definition: "Impossible or difficult to believe.", sentence: "The view from the top was incredible." },
  { word: "leather", level: "One Bee", definition: "Skin of an animal prepared for use.", sentence: "He wore a leather jacket to stay warm." },
  { word: "countess", level: "One Bee", definition: "A woman holding the rank of a count or earl.", sentence: "The countess lived in a grand castle." },
  { word: "nervous", level: "One Bee", definition: "Easily agitated or alarmed.", sentence: "I felt nervous before my presentation." },
  { word: "peppercorn", level: "One Bee", definition: "A dried berry used as a spice.", sentence: "I added a peppercorn to the soup." },
  { word: "cartwheel", level: "One Bee", definition: "A circular sideways handspring.", sentence: "Can you do a perfect cartwheel?" },
  { word: "raise", level: "One Bee", definition: "To lift or move to a higher position.", sentence: "Please raise your hand with a question." },
  { word: "weather", level: "One Bee", definition: "State of the atmosphere at a specific time.", sentence: "The weather is expected to be sunny." },
  { word: "zooming", level: "One Bee", definition: "Moving very quickly.", sentence: "The car was zooming around the track." },
  { word: "attacked", level: "One Bee", definition: "Acted against with physical force.", sentence: "The castle was attacked by the army." },
  { word: "turnout", level: "One Bee", definition: "The number of people attending an event.", sentence: "There was a great turnout for the meeting." },
  { word: "eaten", level: "One Bee", definition: "Put food into the mouth and swallowed.", sentence: "Have you eaten your lunch yet?" },
  { word: "streetlights", level: "One Bee", definition: "Lamps on a pole illuminating a road.", sentence: "The streetlights turn on at dusk." },
  { word: "journey", level: "One Bee", definition: "An act of traveling from one place to another.", sentence: "The journey across the desert was long." },
  { word: "courtyard", level: "One Bee", definition: "An unroofed area enclosed by walls.", sentence: "We sat in the courtyard to enjoy the air." },
  { word: "shouting", level: "One Bee", definition: "Uttering a loud cry.", sentence: "Stop shouting and speak normally." },
  { word: "asleep", level: "One Bee", definition: "In a state of sleep.", sentence: "The baby is finally fast asleep." },
  { word: "curious", level: "One Bee", definition: "Eager to know or learn.", sentence: "The curious kitten explored the box." },
  { word: "dinosaur", level: "One Bee", definition: "A fossil reptile of the Mesozoic era.", sentence: "We saw a huge dinosaur skeleton." },
  { word: "brilliant", level: "One Bee", definition: "Exceptionally clever or talented.", sentence: "She had a brilliant idea for the project." },
  { word: "vacuum", level: "One Bee", definition: "A space entirely devoid of matter.", sentence: "I need to vacuum the rug in the hallway." },
  { word: "gorgeous", level: "One Bee", definition: "Very attractive or beautiful.", sentence: "The flowers in the garden look gorgeous." },
  { word: "monsoon", level: "One Bee", definition: "A seasonal wind bringing heavy rain.", sentence: "The monsoon rains brought needed water." },
  { word: "dangerous", level: "One Bee", definition: "Likely to cause harm or injury.", sentence: "It is dangerous to walk alone at night." },
  { word: "avocado", level: "One Bee", definition: "A pear-shaped fruit with green flesh.", sentence: "I added some avocado to my salad." },
  { word: "valentine", level: "One Bee", definition: "A card or gift sent on Feb 14th.", sentence: "He gave her a special valentine card." },
  { word: "February", level: "One Bee", definition: "The second month of the year.", sentence: "February is the shortest month." },
  { word: "formation", level: "One Bee", definition: "The action of forming something.", sentence: "The planes flew in a tight formation." },
  { word: "especially", level: "One Bee", definition: "To a great extent; very much.", sentence: "I love all fruit, especially berries." },
  { word: "hesitate", level: "Two Bee", definition: "To pause before saying or doing something.", sentence: "Don't hesitate to ask if you need help." },
  { word: "scorcher", level: "Two Bee", definition: "An extremely hot day.", sentence: "Today is a real scorcher, stay hydrated." },
  { word: "scavenger", level: "Two Bee", definition: "An animal that feeds on dead matter or refuse.", sentence: "The vulture is a well-known scavenger." },
  { word: "fragments", level: "Two Bee", definition: "Small parts broken off something.", sentence: "The bowl broke into many small fragments." },
  { word: "deflated", level: "Two Bee", definition: "Having let the air out of something.", sentence: "The balloon deflated slowly overnight." },
  { word: "unleash", level: "Two Bee", definition: "To release from a restraint.", sentence: "Don't unleash the dog in the street." },
  { word: "ration", level: "Two Bee", definition: "A fixed amount of a commodity allowed.", sentence: "The soldiers received a daily ration." },
  { word: "cosmetics", level: "Two Bee", definition: "Products used to improve appearance.", sentence: "She works in a shop that sells cosmetics." },
  { word: "crawdad", level: "Two Bee", origin: "Middle English", definition: "A freshwater crustacean; a crayfish.", sentence: "We found a crawdad in the creek." },
  { word: "frustration", level: "Two Bee", definition: "Feeling upset because of an inability to change something.", sentence: "His frustration grew when the PC crashed." },
  { word: "unruly", level: "Two Bee", definition: "Disorderly and disruptive.", sentence: "The teacher quieted the unruly class." },
  { word: "mascot", level: "Two Bee", definition: "A person or object believed to bring luck.", sentence: "The team's mascot is a friendly tiger." },
  { word: "aroma", level: "Two Bee", definition: "A pleasant, distinctive smell.", sentence: "The aroma of coffee filled the room." },
  { word: "moustache", level: "Two Bee", origin: "French", definition: "Hair grown on a man's upper lip.", sentence: "He decided to grow a moustache." },
  { word: "mustache", level: "Two Bee", origin: "French", definition: "Hair grown on a man's upper lip.", sentence: "He trimmed his mustache carefully." },
  { word: "artifacts", level: "Two Bee", definition: "Objects made by humans of historical interest.", sentence: "The museum displays ancient artifacts." },
  { word: "artefacts", level: "Two Bee", definition: "Objects made by humans of historical interest.", sentence: "Historical artefacts tell us about the past." },
  { word: "perfume", level: "Two Bee", definition: "A fragrant liquid.", sentence: "The flowers had a very sweet perfume." },
  { word: "sinister", level: "Two Bee", definition: "Giving the impression of being evil or harmful.", sentence: "The dark old house looked quite sinister." },
  { word: "tuxedo", level: "Two Bee", definition: "A man's formal dinner jacket.", sentence: "He wore a black tuxedo to the gala." },
  { word: "discoveries", level: "Two Bee", definition: "Acts of finding something for the first time.", sentence: "Scientific discoveries were made recently." },
  { word: "lurches", level: "Two Bee", definition: "Abrupt, unsteady movements.", sentence: "The boat lurches whenever a wave hits." },
  { word: "language", level: "Two Bee", definition: "Method of human communication.", sentence: "Learning a language takes practice." },
  { word: "prognosis", level: "Two Bee", origin: "Greek", definition: "A forecast of the likely course of a disease.", sentence: "The doctor gave a positive prognosis." },
  { word: "Buffalo", level: "Two Bee", definition: "A heavily built wild ox.", sentence: "A herd of Buffalo roamed the plains." },
  { word: "sequins", level: "Two Bee", definition: "Small, shiny disks sewn onto clothing.", sentence: "Her dress was covered in shiny sequins." },
  { word: "gallop", level: "Two Bee", definition: "The fastest pace of a horse.", sentence: "The horse began to gallop across the field." },
  { word: "fabulous", level: "Two Bee", definition: "Extraordinary; wonderful.", sentence: "We had a fabulous time on vacation." },
  { word: "lanky", level: "Two Bee", definition: "Ungracefully thin and tall.", sentence: "The lanky teenager grew very quickly." },
  { word: "fluently", level: "Two Bee", definition: "Ability to express oneself easily.", sentence: "She speaks English and French fluently." },
  { word: "mysterious", level: "Two Bee", definition: "Difficult to understand or explain.", sentence: "The disappearance remained mysterious." },
  { word: "brandished", level: "Two Bee", definition: "Waved something as a threat.", sentence: "The knight brandished his sword." },
  { word: "sardines", level: "Two Bee", definition: "Small silvery food fish.", sentence: "He enjoys eating sardines on toast." },
  { word: "anguish", level: "Two Bee", definition: "Severe mental or physical pain.", sentence: "Her face showed great anguish." },
  { word: "conical", level: "Two Bee", definition: "Shaped like a cone.", sentence: "The mountain had a distinct conical shape." },
  { word: "rickety", level: "Two Bee", definition: "Poorly made and likely to collapse.", sentence: "Be careful on that rickety old ladder." },
  { word: "lilt", level: "Two Bee", definition: "A rhythmic swing or cadence in music or speech.", sentence: "There was a pleasant lilt in her accent." },
  { word: "pediatric", level: "Two Bee", definition: "Relating to the medical care of children.", sentence: "He went to the pediatric clinic." },
  { word: "porridge", level: "Two Bee", definition: "Cereal boiled in water or milk.", sentence: "I like a bowl of porridge for breakfast." },
  { word: "democracy", level: "Two Bee", definition: "Government by the whole population.", sentence: "Every citizen has a voice in a democracy." },
  { word: "rummage", level: "Two Bee", definition: "To search untidily through a mass.", sentence: "I had to rummage through the drawer." },
  { word: "beige", level: "Two Bee", definition: "A pale sandy-fawn color.", sentence: "The office walls were painted beige." },
  { word: "ancestral", level: "Two Bee", definition: "Belonging to or inherited from ancestors.", sentence: "This has been our ancestral home." },
  { word: "grimace", level: "Two Bee", definition: "An ugly, twisted expression on the face.", sentence: "He couldn't help but grimace at the taste." },
  { word: "gaunt", level: "Two Bee", definition: "Lean and haggard from hunger or age.", sentence: "He looked gaunt after being sick." },
  { word: "enormous", level: "Two Bee", definition: "Very large in size.", sentence: "An enormous crowd waited for the gates." },
  { word: "geranium", level: "Two Bee", definition: "A plant with red, pink, or white flowers.", sentence: "She planted a bright red geranium." },
  { word: "nautical", level: "Two Bee", definition: "Relating to sailors or navigation.", sentence: "The room had a nautical theme." },
  { word: "dubious", level: "Two Bee", definition: "Hesitating or doubting.", sentence: "I am dubious about his ability to finish." },
  { word: "ebony", level: "Two Bee", definition: "Very dark, heavy wood.", sentence: "The piano keys were made of black ebony." },
  { word: "foreign", level: "Two Bee", definition: "From a country other than one's own.", sentence: "It is exciting to visit a foreign country." },
  { word: "pantry", level: "Two Bee", definition: "A place where dry goods are kept.", sentence: "We keep all our dry goods in the pantry." },
  { word: "verdict", level: "Two Bee", definition: "A decision on a disputed issue.", sentence: "The jury reached a verdict after debate." },
  { word: "garbled", level: "Two Bee", definition: "Reproduced in a confused and distorted way.", sentence: "The radio signal was garbled." },
  { word: "encourages", level: "Two Bee", definition: "Gives support or confidence.", sentence: "The coach always encourages the players." },
  { word: "imitation", level: "Two Bee", definition: "Using someone as a model; a copy.", sentence: "This is an imitation of a famous painting." },
  { word: "miniature", level: "Two Bee", definition: "Very small of its kind.", sentence: "She collects miniature furniture." },
  { word: "receptionist", level: "Two Bee", definition: "Person who greets visitors in an office.", sentence: "The receptionist greeted us warmly." },
  { word: "preamble", level: "Two Bee", definition: "An introductory statement.", sentence: "The preamble explains the document." },
  { word: "plausible", level: "Two Bee", definition: "Seeming reasonable or probable.", sentence: "His explanation sounded plausible." },
  { word: "reprimanding", level: "Two Bee", definition: "Rebuking someone officially.", sentence: "The boss was reprimanding the staff." },
  { word: "commotion", level: "Two Bee", definition: "A state of confused and noisy disturbance.", sentence: "There was a loud commotion in the hall." },
  { word: "oblivion", level: "Two Bee", definition: "State of being unaware or unconscious.", sentence: "The city fell into oblivion over time." },
  { word: "immigrants", level: "Two Bee", definition: "People who live permanently in a foreign country.", sentence: "The town was founded by immigrants." },
  { word: "steeple", level: "Two Bee", definition: "A tall tower on a church roof.", sentence: "The church steeple was visible for miles." },
  { word: "spectators", level: "Two Bee", definition: "People who watch an event.", sentence: "Thousands of spectators watched the race." },
  { word: "lanyards", level: "Two Bee", definition: "Cords worn around the neck to hold items.", sentence: "Students wore IDs on colorful lanyards." },
  { word: "suspicious", level: "Two Bee", definition: "Having a cautious distrust.", sentence: "The police were suspicious of his behavior." },
  { word: "parchment", level: "Two Bee", definition: "Animal skin used as a writing surface.", sentence: "The old map was drawn on parchment." },
  { word: "ramshackle", level: "Two Bee", definition: "In a state of severe disrepair.", sentence: "They lived in a ramshackle hut." },
  { word: "fugitive", level: "Two Bee", definition: "A person who has escaped from a place.", sentence: "The police searched for the fugitive." },
  { word: "heron", level: "Two Bee", definition: "A large fish-eating bird with long legs.", sentence: "A tall heron stood still in the water." },
  { word: "dissolving", level: "Two Bee", definition: "Becoming part of a liquid solution.", sentence: "Sugar is dissolving in the hot tea." },
  { word: "nomad", level: "Two Bee", definition: "A person with no permanent home.", sentence: "The nomad moved his tent to a new spot." },
  { word: "billowed", level: "Two Bee", definition: "Swelled outward with air.", sentence: "Smoke billowed out of the factory." },
  { word: "skewer", level: "Two Bee", definition: "A long pin for holding food together.", sentence: "Put the meat onto a metal skewer." },
  { word: "Berlin", level: "Two Bee", definition: "The capital city of Germany.", sentence: "Berlin is a city with a rich history." },
  { word: "lunacy", level: "Two Bee", definition: "Insanity; great foolishness.", sentence: "It would be pure lunacy to go out now." },
  { word: "conjure", level: "Two Bee", definition: "To call upon a spirit or make something appear.", sentence: "The magician seemed to conjure a rabbit." },
  { word: "bracken", level: "Two Bee", definition: "A tall, coarse fern.", sentence: "The hillside was covered in green bracken." },
  { word: "noggin", level: "Two Bee", definition: "A person's head.", sentence: "He bumped his noggin on the doorway." },
  { word: "neon", level: "Two Bee", definition: "A fluorescent light; a chemical element.", sentence: "The city was bright with colorful neon." },
  { word: "rakish", level: "Two Bee", definition: "Dashing or jaunty in appearance.", sentence: "He wore his hat at a rakish angle." },
  { word: "hypnosis", level: "Two Bee", definition: "A trance-like state of focus.", sentence: "Some people use hypnosis to quit smoking." },
  { word: "rotunda", level: "Two Bee", definition: "A round building or room.", sentence: "The building has a grand central rotunda." },
  { word: "gusto", level: "Two Bee", definition: "Zest and enjoyment in doing something.", sentence: "He ate his dinner with great gusto." },
  { word: "toiletries", level: "Two Bee", definition: "Articles used in washing and grooming.", sentence: "Don't forget to pack your toiletries." },
  { word: "gleaned", level: "Two Bee", definition: "Information extracted from various sources.", sentence: "Info was gleaned from the old records." },
  { word: "jeered", level: "Two Bee", definition: "Made rude and mocking remarks.", sentence: "The crowd jeered at the missed shot." },
  { word: "winsome", level: "Two Bee", definition: "Attractive or appealing in character.", sentence: "She had a winsome smile everyone liked." },
  { word: "prattling", level: "Two Bee", definition: "Talking at length in a foolish way.", sentence: "The child was prattling about his toy." },
  { word: "galore", level: "Two Bee", definition: "In abundance.", sentence: "There were prizes galore at the fair." },
  { word: "emporium", level: "Two Bee", definition: "A large retail store with variety.", sentence: "We visited a large clothing emporium." },
  { word: "atrium", level: "Two Bee", definition: "An open-roofed central hall.", sentence: "The hotel has a beautiful glass atrium." },
  { word: "eccentric", level: "Two Bee", definition: "Unconventional and slightly strange.", sentence: "The old man had eccentric habits." },
  { word: "savant", level: "Two Bee", definition: "A person of great specialized knowledge.", sentence: "He is a mathematical savant." },
  { word: "gangly", level: "Three Bee", definition: "Tall, thin, and awkward.", sentence: "The gangly foal struggled to stand." },
  { word: "swaggering", level: "Three Bee", definition: "Walking in a very confident, arrogant way.", sentence: "He came swaggering into the room." },
  { word: "chimneys", level: "Three Bee", definition: "Vertical pipes for smoke.", sentence: "Smoke rose from all the chimneys." },
  { word: "riveted", level: "Three Bee", definition: "Held fast; fascinated.", sentence: "I was riveted by the exciting story." },
  { word: "plaid", level: "Three Bee", definition: "A fabric with a checkered pattern.", sentence: "He wore a red and black plaid shirt." },
  { word: "dirge", level: "Three Bee", definition: "A mournful song for the dead.", sentence: "The choir sang a mournful dirge." },
  { word: "zeal", level: "Three Bee", definition: "Great energy or enthusiasm.", sentence: "She approached the project with zeal." },
  { word: "whittled", level: "Three Bee", definition: "Carved wood into an object.", sentence: "He whittled a bird out of wood." },
  { word: "depots", level: "Three Bee", definition: "Places where supplies are stored.", sentence: "The company has several storage depots." },
  { word: "fiberglass", level: "Three Bee", definition: "Reinforced plastic with glass fibers.", sentence: "The boat hull is made of fiberglass." },
  { word: "salvaged", level: "Three Bee", definition: "Rescued from potential loss.", sentence: "Cargo was salvaged from the wreck." },
  { word: "fissures", level: "Three Bee", definition: "Long, narrow cracks or openings.", sentence: "Fissures appeared in the ground." },
  { word: "enthusiastic", level: "Three Bee", definition: "Showing intense enjoyment.", sentence: "The crowd gave them an enthusiastic welcome." },
  { word: "discipline", level: "Three Bee", definition: "Training to obey rules.", sentence: "It takes discipline to practice daily." },
  { word: "unfamiliar", level: "Three Bee", definition: "Not known or recognized.", sentence: "I felt lost in the unfamiliar city." },
  { word: "scurrying", level: "Three Bee", definition: "Moving hurriedly with short steps.", sentence: "I saw a mouse scurrying across the floor." },
  { word: "dignitaries", level: "Three Bee", definition: "People of high rank or office.", sentence: "Local dignitaries attended the opening." },
  { word: "pizzeria", level: "Three Bee", definition: "A place where pizzas are sold.", sentence: "We went to the new pizzeria for dinner." },
  { word: "dismissal", level: "Three Bee", definition: "Act of allowing someone to leave.", sentence: "The meeting ended with a formal dismissal." },
  { word: "skittish", level: "Three Bee", definition: "Excitable or easily scared.", sentence: "The noise made the horse skittish." },
  { word: "careened", level: "Three Bee", definition: "Tilted or moved uncontrollably.", sentence: "The car careened off the road." },
  { word: "nomination", level: "Three Bee", definition: "Formal suggestion for an award or office.", sentence: "She was thrilled by her nomination." },
  { word: "opportunist", level: "Three Bee", definition: "Person who takes advantage of circumstances.", sentence: "He is an opportunist who takes every chance." },
  { word: "dictatorship", level: "Three Bee", definition: "Government by a ruler with total power.", sentence: "The country was under a dictatorship." },
  { word: "comrades", level: "Three Bee", definition: "Fellow members or companions.", sentence: "He remains close to his old comrades." },
  { word: "sporadic", level: "Three Bee", definition: "Occurring at irregular intervals.", sentence: "There was sporadic gunfire in the night." },
  { word: "promenade", level: "Three Bee", definition: "A paved public walk by a waterfront.", sentence: "We took a walk along the promenade." },
  { word: "repugnant", level: "Three Bee", definition: "Extremely distasteful or unacceptable.", sentence: "Hurting anyone is repugnant to me." },
  { word: "invincible", level: "Three Bee", definition: "Too powerful to be defeated.", sentence: "The team seemed invincible this year." },
  { word: "renowned", level: "Three Bee", definition: "Known or talked about by many; famous.", sentence: "He is a renowned expert in science." },
  { word: "parachute", level: "Three Bee", definition: "Cloth canopy used for safe descent.", sentence: "He used his parachute to land safely." },
  { word: "laborious", level: "Three Bee", definition: "Requiring much effort and time.", sentence: "The garden work was a laborious task." },
  { word: "appointment", level: "Three Bee", definition: "Arrangement to meet at a certain time.", sentence: "I have a dentist appointment today." },
  { word: "foreseeable", level: "Three Bee", definition: "Able to be predicted.", sentence: "Nothing will change in the foreseeable future." },
  { word: "ratify", level: "Three Bee", definition: "To sign or give formal consent to.", sentence: "The government is expected to ratify it." },
  { word: "scalpel", level: "Three Bee", definition: "A small, sharp knife used in surgery.", sentence: "The surgeon used a sharp scalpel." },
  { word: "reclusive", level: "Three Bee", definition: "Avoiding the company of others.", sentence: "The author became reclusive in old age." },
  { word: "compassionate", level: "Three Bee", definition: "Showing sympathy and concern.", sentence: "She is a compassionate person." },
  { word: "bulletin", level: "Three Bee", definition: "A short official statement.", sentence: "A news bulletin interrupted the show." },
  { word: "alfalfa", level: "Three Bee", definition: "A plant used as livestock fodder.", sentence: "The farmer harvested the alfalfa." },
  { word: "officially", level: "Three Bee", definition: "In a formal and public way.", sentence: "The park was officially opened today." },
  { word: "crematorium", level: "Three Bee", definition: "Place where bodies are cremated.", sentence: "The service was at the crematorium." },
  { word: "bayonet", level: "Three Bee", definition: "A blade fixed to the end of a rifle.", sentence: "The soldier fixed a bayonet to his rifle." },
  { word: "amicable", level: "Three Bee", definition: "Friendly and without disagreement.", sentence: "They reached an amicable agreement." },
  { word: "exuberant", level: "Three Bee", definition: "Filled with energy and excitement.", sentence: "The exuberant fans cheered loudly." },
  { word: "beautician", level: "Three Bee", definition: "A person giving beauty treatments.", sentence: "The beautician gave her a facial." },
  { word: "equations", level: "Three Bee", definition: "Mathematical statements of equality.", sentence: "We solved quadratic equations today." },
  { word: "assignment", level: "Three Bee", definition: "A task or piece of work.", sentence: "I need to finish my history assignment." },
  { word: "ultimatum", level: "Three Bee", definition: "A final demand or statement of terms.", sentence: "The company issued an ultimatum." },
  { word: "whinnying", level: "Three Bee", definition: "A gentle, high-pitched horse sound.", sentence: "We heard the horses whinnying." },
  { word: "squalor", level: "Three Bee", definition: "State of being extremely dirty.", sentence: "The family was living in terrible squalor." },
  { word: "memoirs", level: "Three Bee", definition: "Biography written from personal knowledge.", sentence: "He is writing his memoirs of politics." },
  { word: "cylinders", level: "Three Bee", definition: "Solid geometric figures with circular ends.", sentence: "The engine has six high-performance cylinders." },
  { word: "ominous", level: "Three Bee", definition: "Giving the impression something bad will happen.", sentence: "The dark clouds looked very ominous." },
  { word: "muffler", level: "Three Bee", definition: "A scarf; also a silencer for an engine.", sentence: "He wore a thick wool muffler." },
  { word: "syndrome", level: "Three Bee", definition: "A group of symptoms occurring together.", sentence: "The doctor identified a rare syndrome." },
  { word: "premises", level: "Three Bee", definition: "A house or building and its land.", sentence: "You must leave the premises immediately." },
  { word: "safari", level: "Three Bee", definition: "Expedition to observe animals in the wild.", sentence: "We went on safari to see lions." },
  { word: "lasagna", level: "Three Bee", definition: "Baked pasta with layers of meat and cheese.", sentence: "She made a delicious meat lasagna." },
  { word: "substantially", level: "Three Bee", definition: "To a great or significant degree.", sentence: "Costs have increased substantially." },
  { word: "mercantile", level: "Three Bee", definition: "Relating to trade or merchants.", sentence: "The city has a long mercantile history." },
  { word: "formidable", level: "Three Bee", definition: "Inspiring fear or respect.", sentence: "He is a formidable opponent." },
  { word: "propaganda", level: "Three Bee", definition: "Biased info used to promote a cause.", sentence: "The government used propaganda." },
  { word: "marquee", level: "Three Bee", definition: "A large tent; a roof projection over an entrance.", sentence: "We stood under the marquee for shelter." },
  { word: "proficient", level: "Three Bee", definition: "Competent or skilled in doing something.", sentence: "She is very proficient at piano." },
  { word: "compunction", level: "Three Bee", definition: "A feeling of guilt or hesitation.", sentence: "He felt no compunction about lying." },
  { word: "emphatically", level: "Three Bee", definition: "In a forceful way.", sentence: "She emphatically denied involvement." },
  { word: "hyperventilated", level: "Three Bee", definition: "Breathed at an abnormally rapid rate.", sentence: "She hyperventilated during the panic." },
  { word: "ostracism", level: "Three Bee", definition: "Exclusion from a group.", sentence: "He suffered ostracism after the scandal." },
  { word: "onslaught", level: "Three Bee", definition: "A fierce or destructive attack.", sentence: "They struggled with the onslaught." },
  { word: "ruefully", level: "Three Bee", definition: "Expressing sorrow or regret.", sentence: "He looked ruefully at the broken vase." },
  { word: "misanthrope", level: "Three Bee", origin: "French/Greek", definition: "Someone who dislikes or avoids human society.", sentence: "The hermit was a well-known misanthrope." },
  { word: "prototype", level: "Three Bee", definition: "A first or preliminary model.", sentence: "They built a prototype of the car." },
  { word: "cravenly", level: "Three Bee", definition: "In a cowardly manner.", sentence: "He cravenly abandoned his friends." },
  { word: "mulberry", level: "Three Bee", definition: "A dark red or white edible berry.", sentence: "The mulberry tree is full of fruit." },
  { word: "hypocritical", level: "Three Bee", definition: "Behaving against one's stated standards.", sentence: "It is hypocritical to tell others what to do." },
  { word: "chlorine", level: "Three Bee", definition: "A chemical used for disinfection.", sentence: "The smell of chlorine was strong." },
  { word: "traumatic", level: "Three Bee", definition: "Deeply disturbing or distressing.", sentence: "It was a very traumatic experience." },
  { word: "receipts", level: "Three Bee", definition: "Written proofs of purchase.", sentence: "Please keep your receipts for expenses." },
  { word: "solemnly", level: "Three Bee", definition: "In a formal and dignified manner.", sentence: "The judge solemnly read the sentence." },
  { word: "begrudge", level: "Three Bee", definition: "To give or allow reluctantly.", sentence: "I do not begrudge him his success." },
  { word: "contentious", level: "Three Bee", definition: "Causing or likely to cause an argument.", sentence: "The new law is a contentious issue." },
  { word: "precocious", level: "Three Bee", definition: "Developing abilities at an earlier age than usual.", sentence: "The precocious child read at age three." },
  { word: "ensemble", level: "Three Bee", definition: "A group of performers who work together.", sentence: "The jazz ensemble played a great set." },
  { word: "cadre", level: "Three Bee", definition: "A small group of people trained for a purpose.", sentence: "A cadre of experts was formed." },
  { word: "lye", level: "Three Bee", definition: "A strong alkaline solution for cleaning.", sentence: "She used lye to clean the old pipes." },
  { word: "belfry", level: "Three Bee", definition: "The part of a tower where bells hang.", sentence: "Bats live up in the church belfry." },
  { word: "lacrosse", level: "Three Bee", definition: "Team sport using a stick with a net pocket.", sentence: "He plays lacrosse for the team." },
  { word: "sluice", level: "Three Bee", definition: "A sliding gate for controlling water flow.", sentence: "They opened the sluice to let water out." },
  { word: "cajolery", level: "Three Bee", definition: "Flattery used to persuade.", sentence: "He used cajolery to get what he wanted." },
  { word: "vigilance", level: "Three Bee", definition: "State of keeping careful watch.", sentence: "Constant vigilance is needed for security." },
  { word: "residuals", level: "Three Bee", definition: "Amounts remaining after the main part is gone.", sentence: "The actor receives residuals from the show." },
  { word: "boutique", level: "Three Bee", definition: "A small shop selling fashionable items.", sentence: "She bought her dress at a boutique." },
  { word: "peroxide", level: "Three Bee", definition: "A chemical used for bleaching or as an antiseptic.", sentence: "Use peroxide to clean the small cut." },
  { word: "aristocracy", level: "Three Bee", definition: "The highest class in society.", sentence: "The land was owned by the aristocracy." },
  { word: "apocalypse", level: "Three Bee", definition: "Event involving total destruction.", sentence: "The movie was about a global apocalypse." },
  { word: "almanac", level: "Three Bee", definition: "Annual calendar with important dates.", sentence: "I checked the almanac for sunrise times." },
  { word: "hippies", level: "Three Bee", definition: "People of the 60s rejecting conventional values.", sentence: "The festival attracted many hippies." },
  { word: "samosas", level: "Three Bee", definition: "Triangular fried pastries with savory filling.", sentence: "We had spicy vegetable samosas." },
  { word: "campaign", level: "Three Bee", definition: "Organized actions to achieve a goal.", sentence: "The political campaign lasted months." },
  { word: "pistachio", level: "Three Bee", definition: "A small savory nut with a green kernel.", sentence: "He chose pistachio ice cream." },
  { word: "mosque", level: "Three Bee", definition: "A Muslim place of worship.", sentence: "The mosque has a beautiful minaret." },
  { word: "zombielike", level: "Three Bee", definition: "Being unresponsive or dazed.", sentence: "He walked around in a zombielike state." },
  { word: "warlock", level: "Three Bee", origin: "Middle English/Old Norse", definition: "A male practitioner of evil magic.", sentence: "The villain was an evil warlock." },
  { word: "colossus", level: "Three Bee", definition: "A person or thing of enormous size.", sentence: "The huge statue was a true colossus." },
  { word: "convulsively", level: "Three Bee", definition: "In a jerky, uncontrollable way.", sentence: "Her body shook convulsively." },
  { word: "dimensional", level: "Three Bee", definition: "Relating to measurements in space.", sentence: "It was a complex dimensional problem." },
  { word: "garishly", level: "Three Bee", definition: "In a bright, showy, or gaudy way.", sentence: "The room was garishly decorated." },
  { word: "graffitist", level: "Three Bee", definition: "A person who creates graffiti.", sentence: "The graffitist painted a mural." },
  { word: "Everest", level: "Three Bee", definition: "The highest mountain on Earth.", sentence: "Mount Everest is a dream for many." },
  { word: "dexterity", level: "Three Bee", definition: "Skill in performing tasks with hands.", sentence: "He handled tools with great dexterity." },
  { word: "cavorting", level: "Three Bee", definition: "Jumping or dancing around excitedly.", sentence: "Children were cavorting on the beach." },
  { word: "marauder", level: "Three Bee", definition: "A person who prowls for loot.", sentence: "The marauder attacked at night." },
  { word: "conscience", level: "Three Bee", definition: "Inner sense of right and wrong.", sentence: "His conscience told him he was wrong." },
  { word: "battlements", level: "Three Bee", definition: "Low walls on a castle with firing gaps.", sentence: "We walked along the battlements." },
  { word: "deferential", level: "Three Bee", definition: "Showing respect and humble submission.", sentence: "He was always deferential to elders." },
  { word: "albatross", level: "Three Bee", definition: "A large oceanic bird.", sentence: "An albatross followed our ship." },
  { word: "khaki", level: "Three Bee", definition: "A dull brownish-yellow fabric.", sentence: "The soldiers wore uniforms of khaki." },
  { word: "opalescent", level: "Three Bee", definition: "Showing colors like an opal stone.", sentence: "The sea looked opalescent in the light." },
  { word: "asphalt", level: "Three Bee", definition: "Dark sticky substance for roads.", sentence: "The road was paved with smooth asphalt." },
  { word: "Yiddish", level: "Three Bee", origin: "Yiddish", definition: "A language used by Jewish people of Europe before the Holocaust.", sentence: "My grandfather speaks a little Yiddish." },
  { word: "talcum", level: "Three Bee", definition: "A soft powder for the skin.", sentence: "She used talcum powder after her shower." },
  { word: "tranquilizer", level: "Three Bee", definition: "Drug used to reduce anxiety.", sentence: "The vet gave the lion a tranquilizer." },
  { word: "equestrian", level: "Three Bee", definition: "Relating to horse riding.", sentence: "She is a talented equestrian." },
  { word: "plaited", level: "Three Bee", definition: "Braided or intertwined.", sentence: "She wore her hair in a plaited style." },
  { word: "monsieur", level: "Three Bee", origin: "French", definition: "Title for a French-speaking man.", sentence: "'Good evening, monsieur,' said the manager." },
  { word: "manticores", level: "Three Bee", definition: "Mythical beasts with human heads and lion bodies.", sentence: "The book described mythical manticores." },
  { word: "prestigious", level: "Three Bee", definition: "Inspiring respect and high status.", sentence: "He went to a prestigious university." },
  { word: "fraidycat", level: "Three Bee", definition: "A person who is easily scared.", sentence: "Don't be a fraidycat, come in." },
  { word: "guttural", level: "Three Bee", definition: "Harsh sound produced in the throat.", sentence: "He spoke in a deep, guttural voice." },
  { word: "lo mein", level: "Three Bee", definition: "A Chinese noodle dish.", sentence: "I ordered chicken lo mein for lunch." },
  { word: "courier", level: "Three Bee", definition: "A messenger who carries documents.", sentence: "The courier delivered the package." },
  { word: "sans serif", level: "Three Bee", definition: "A font style without decorative lines.", sentence: "This doc is in a sans serif font." },
  { word: "psyche", level: "Three Bee", origin: "Greek", definition: "The human soul, mind, or spirit.", sentence: "Psychology explores the human psyche." },
  { word: "stucco", level: "Three Bee", definition: "Plaster used for coating walls.", sentence: "The house had white stucco walls." },
  { word: "Frankenstein", level: "Three Bee", definition: "A thing that destroys its creator.", sentence: "He created a monster like Frankenstein." },
  { word: "schema", level: "Three Bee", definition: "A plan or outline of a theory.", sentence: "We need a clear schema for the system." },
  { word: "et cetera", level: "Three Bee", definition: "And other similar things.", sentence: "We need pens, paper, et cetera." },
  { word: "vidimus", level: "Three Bee", definition: "An inspection of a document.", sentence: "He performed a vidimus of the records." },
  { word: "delphine", level: "Three Bee", definition: "Relating to dolphins.", sentence: "The research focused on delphine behavior." },
  { word: "slough", level: "Three Bee", definition: "A swamp; also a state of despair.", sentence: "The path became a muddy slough." },
  { word: "archipelago", level: "Three Bee", origin: "Greek/Italian", definition: "A group or chain of islands.", sentence: "The country is a large archipelago." },
  { word: "serape", level: "Three Bee", definition: "A colorful woolen shawl.", sentence: "He wore a brightly colored serape." },
  { word: "sarape", level: "Three Bee", definition: "A colorful woolen shawl.", sentence: "The weaver finished a traditional sarape." },
  { word: "puissance", level: "Three Bee", definition: "Great power or influence.", sentence: "The king showed great puissance." },
  { word: "pinioning", level: "Three Bee", definition: "Tying or holding someone's arms.", sentence: "He was pinioning the suspect's arms." },
  { word: "chignon", level: "Three Bee", origin: "French", definition: "A knot or coil of hair (pronounced sheen-yon).", sentence: "She wore her hair in a stylish chignon." },
  { word: "pheromone", level: "Three Bee", definition: "Chemical released by an animal to affect others.", sentence: "The insect released a pheromone." },
  { word: "galleon", level: "Three Bee", definition: "A large Spanish sailing ship.", sentence: "The Spanish galleon was loaded with gold." },
  { word: "magnanimous", level: "Three Bee", definition: "Generous or forgiving toward a rival.", sentence: "It was magnanimous of her to forgive him." },
  { word: "chartreuse", level: "Three Bee", definition: "A pale yellow or green color.", sentence: "The walls were painted chartreuse." },
  { word: "wainscoting", level: "Three Bee", definition: "Wood paneling on the lower part of a wall.", sentence: "The room has elegant wainscoting." },
  { word: "Nehru", level: "Three Bee", origin: "Hindi", definition: "Named after Jawaharlal Nehru; refers to a specific style of collar/jacket.", sentence: "He wore a traditional Nehru jacket." },
  { word: "tuberculosis", level: "Three Bee", definition: "Serious disease affecting the lungs.", sentence: "He was in the hospital for tuberculosis." },
  { word: "barricade", level: "Three Bee", definition: "An improvised barrier.", sentence: "Protesters built a barricade." },
  { word: "confreres", level: "Three Bee", definition: "Colleagues or fellow members.", sentence: "He discussed it with his confreres." },
  { word: "anonymously", level: "Three Bee", definition: "Without revealing a name.", sentence: "The donation was given anonymously." },
  { word: "unparalleled", level: "Three Bee", definition: "Having no equal; exceptional.", sentence: "His success was truly unparalleled." },
  { word: "barrette", level: "Three Bee", definition: "A clip for holding hair.", sentence: "She used a barrette to hold her hair back." },
  { word: "chassis", level: "Three Bee", origin: "French", definition: "The base frame of a vehicle.", sentence: "The mechanic checked the chassis." },
  { word: "junket", level: "Three Bee", definition: "An extravagant trip at public expense.", sentence: "The trip was criticized as a junket." },
  { word: "quandary", level: "Three Bee", definition: "A state of uncertainty; a dilemma.", sentence: "I am in a quandary about the job offer." },
  { word: "Erie", level: "Three Bee", definition: "One of the five Great Lakes.", sentence: "We took a boat trip across Lake Erie." },
  { word: "gingham", level: "Three Bee", definition: "Lightweight checked cotton cloth.", sentence: "She wore a blue and white gingham dress." },
  { word: "silhouette", level: "Three Bee", definition: "Dark shape of someone against a light background.", sentence: "I saw the silhouette of a man." },
  { word: "auxiliary", level: "Three Bee", definition: "Providing additional help.", sentence: "We used an auxiliary generator." },
  { word: "thesaurus", level: "Three Bee", origin: "Latin/Greek", definition: "A book of synonyms.", sentence: "I used a thesaurus for a better word." },
  { word: "patriarchs", level: "Three Bee", definition: "Male heads of a family or group.", sentence: "The patriarchs led their people." },
  { word: "chandelier", level: "Three Bee", definition: "A decorative hanging light fixture.", sentence: "A grand chandelier hung from the ceiling." },
  { word: "dulce", level: "Three Bee", origin: "Spanish", definition: "Sweet; often referring to a sweet food or drink.", sentence: "We had sweet dulce de leche." },
  { word: "concierge", level: "Three Bee", origin: "French", definition: "A hotel staff member or caretaker.", sentence: "The concierge booked a table for us." },
  { word: "latticework", level: "Three Bee", definition: "Interlacing strips of wood or metal.", sentence: "The porch had white latticework." },
  { word: "hibiscus", level: "Three Bee", definition: "Plant with large colorful flowers.", sentence: "The hibiscus flowers were bright red." },
  { word: "tamale", level: "Three Bee", origin: "Spanish/Nahuatl", definition: "Cornmeal dough with meat steamed in husks.", sentence: "I ordered a spicy pork tamale." },
  { word: "maracas", level: "Three Bee", origin: "Spanish/Guarani", definition: "Gourd rattles used in music.", sentence: "The band played with traditional maracas." },
  { word: "gyroplane", level: "Three Bee", definition: "Aircraft with a free-spinning rotor.", sentence: "A gyroplane landed at the airfield." },
  { word: "burpees", level: "Three Bee", definition: "An exercise involving a squat and a leap.", sentence: "We did fifty burpees in gym class." },
  { word: "Adriatic", level: "Three Bee", definition: "Referring to the sea between Italy and the Balkans.", sentence: "We cruised through the Adriatic Sea." },
  { word: "piccolo", level: "Three Bee", origin: "Italian", definition: "A small flute.", sentence: "She plays the piccolo in the orchestra." },
  { word: "au revoir", level: "Three Bee", origin: "French", definition: "A French word for 'goodbye' (literally 'until we see again').", sentence: "'Au revoir,' he said as he left." },
  { word: "tulle", level: "Three Bee", origin: "French", definition: "A soft, fine silk or nylon net.", sentence: "Her skirt was made of layers of tulle." },
  { word: "bol weevil", level: "Three Bee", definition: "A beetle that feeds on cotton.", sentence: "The bol weevil destroyed the cotton." },
  { word: "camphor", level: "Three Bee", definition: "Substance used in medicine and mothballs.", sentence: "The smell of camphor was strong." },
  { word: "Tucson", level: "Three Bee", definition: "A city in Arizona.", sentence: "We spent vacation in Tucson, Arizona." },
  { word: "paparazzi", level: "Three Bee", origin: "Italian", definition: "Freelance photographers who pursue celebrities.", sentence: "The star was surrounded by paparazzi." },
  { word: "pumpernickel", level: "Three Bee", origin: "German", definition: "A dark, dense rye bread.", sentence: "I like dark pumpernickel bread." },
  { word: "pogrom", level: "Three Bee", definition: "Organized massacre of an ethnic group.", sentence: "Many people fled the country's pogrom." },
  { word: "bursitis", level: "Three Bee", definition: "Inflammation of a joint bursa.", sentence: "He stopped playing due to bursitis." },
  { word: "pâtisserie", level: "Three Bee", origin: "French", definition: "A French pastry shop.", sentence: "We bought croissants at the pâtisserie." },
  { word: "cycads", level: "Three Bee", definition: "Palm-like plants with cones.", sentence: "The garden featured rare cycads." },
  { word: "sarsaparilla", level: "Three Bee", origin: "Spanish/New World", definition: "Soft drink flavored with plant roots.", sentence: "I tried an old-fashioned sarsaparilla." },
  { word: "maître d'", level: "Three Bee", origin: "French", definition: "Head of a restaurant dining room (short for maître d'hôtel).", sentence: "The maître d' showed us to our table." },
  { word: "cannelloni", level: "Three Bee", origin: "Italian", definition: "Large pasta tubes stuffed with meat or cheese.", sentence: "The cannelloni was stuffed with ricotta." },
  { word: "boulangerie", level: "Three Bee", origin: "French", definition: "A French bakery.", sentence: "We went to the boulangerie for bread." },
  { word: "bronchitis", level: "Three Bee", definition: "Inflammation of the bronchial tubes.", sentence: "She had a cough from her bronchitis." },
  { word: "Oswego", level: "Three Bee", definition: "A port city in New York.", sentence: "He went to college in Oswego, New York." },
  { word: "diphtheria", level: "Three Bee", origin: "Greek", definition: "Contagious disease of the throat.", sentence: "Children were vaccinated for diphtheria." },
  { word: "baklava", level: "Three Bee", origin: "Turkish", definition: "Layered pastry with nuts and honey.", sentence: "We had sweet baklava for dessert." },
  { word: "corbels", level: "Three Bee", definition: "Stone or wood projections from a wall.", sentence: "The roof was supported by carved corbels." },
  { word: "trebuchets", level: "Three Bee", definition: "Medieval siege machines for throwing stones.", sentence: "The army used large trebuchets." },
  { word: "Kilimanjaro", level: "Three Bee", origin: "Swahili", definition: "Highest mountain in Africa.", sentence: "Mount Kilimanjaro is a major challenge." },
  { word: "fräulein", level: "Three Bee", origin: "German", definition: "Title for an unmarried German woman.", sentence: "'Excuse me, fräulein,' said the stranger." },
  { word: "protégé", level: "Three Bee", origin: "French", definition: "A person guided by an older, more experienced person.", sentence: "He is the protégé of a famous pianist." },
  { word: "hors d'oeuvres", level: "Three Bee", origin: "French", definition: "Appetizers (literally 'outside the work').", sentence: "They served hors d'oeuvres before dinner." },
  { word: "maquisards", level: "Three Bee", definition: "French resistance fighters.", sentence: "The maquisards fought bravely." },
  { word: "Aubusson", level: "Three Bee", definition: "Fine woven tapestry or carpet.", sentence: "The floor had an Aubusson rug." },
  { word: "Charolais", level: "Three Bee", definition: "A breed of large white cattle.", sentence: "The farm raises Charolais cattle." },
  { word: "Charollais", level: "Three Bee", definition: "A breed of large white cattle.", sentence: "A Charollais sheep was seen in the meadow." }
];